### ISSUE TITLE
Cannot build packages with current master

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#350] opened 2020-05-13 13:38 UTC
**Description**

I'm probably missing something, but building any Ska packages is failing completely for me now on skare3 master.  I tried:

- skare3 master on kady and on MacOS building Ska.ftp (fail, see log below)
- skare3 master on kady building ska_helpers (`LookupError: setuptools-scm was unable to detect version for '/data/baffin/tom/git/skare3/builds/ska_helpers_1589376650055/work'`)
- skare3 master on MacOS building ska_helpers (fail)
- skare3 shiny branch on MacOS building Ska.ftp and ska_helpers (success)
- skare3 shiny branch on linux (kady) building ska_helpers  

I can provide more details of the other failures but there might be a systemic problem that will just fix it all.

**To Reproduce**

#### Linux, skare3 master, Ska.ftp

- Log in to kady
- Activate ska3 environment
- Change to skare3 git repo
- Check out latest master (d792e1c)
- `python ska_builder.py Ska.ftp`

```
ska3-kady$ python ska_builder.py Ska.ftp
- Building package Ska.ftp.
  - Cloning or updating source source Ska.ftp.
Enter passphrase for key '/home/aldcroft/.ssh/id_rsa': 
  - Cloned from url git@github.com:sot/Ska.ftp
  - Auto-checked out at 3.5.3 which is also tip of master
zip_safe flag not set; analyzing archive contents...
  - SKA_PKG_VERSION=3.5.3
  - conda build /data/baffin/tom/git/skare3/pkg_defs/Ska.ftp --croot /data/baffin/tom/git/skare3/builds --no-test --old-build-string --no-anaconda-upload --numpy 1.12 --perl 5.26.2 --skip-existing
Attempting to finalize metadata for ska.ftp
INFO:conda_build.metadata:Attempting to finalize metadata for ska.ftp
BUILD START: ['ska.ftp-3.5.3-py_0.tar.bz2']

The following NEW packages will be INSTALLED:

    certifi:        2016.2.28-py36_0
    openssl:        1.0.2l-0        
    pip:            9.0.1-py36_1    
    python:         3.6.2-0         
    readline:       6.2-2           
    setuptools:     36.4.0-py36_1   
    setuptools_scm: 1.15.0-py36_0   
    sqlite:         3.13.0-0        
    tk:             8.5.18-0        
    wheel:          0.29.0-py36_0   
    xz:             5.2.3-0         
    zlib:           1.2.11-0        

Copying /data/baffin/tom/git/skare3/src/Ska.ftp to /data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/work
source tree in: /data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/work
+ export CONDA_BUILD=1
+ CONDA_BUILD=1
+ export PYTHONNOUSERSITE=1
+ PYTHONNOUSERSITE=1
+ export CONDA_DEFAULT_ENV=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
+ CONDA_DEFAULT_ENV=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
+ export ARCH=64
+ ARCH=64
+ export PREFIX=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
+ PREFIX=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
+ export BUILD_PREFIX=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
+ BUILD_PREFIX=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
+ export SYS_PREFIX=/proj/sot/ska3/flight
+ SYS_PREFIX=/proj/sot/ska3/flight
+ export SYS_PYTHON=/proj/sot/ska3/flight/bin/python
+ SYS_PYTHON=/proj/sot/ska3/flight/bin/python
+ export SUBDIR=linux-64
+ SUBDIR=linux-64
+ export SRC_DIR=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/work
+ SRC_DIR=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/work
+ export ROOT=/proj/sot/ska3/flight
+ ROOT=/proj/sot/ska3/flight
+ export CONDA_PY=36
+ CONDA_PY=36
+ export PY3K=1
+ PY3K=1
+ export PY_VER=3.6
+ PY_VER=3.6
+ export STDLIB_DIR=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.6
+ STDLIB_DIR=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.6
+ export SP_DIR=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.6/site-packages
+ SP_DIR=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.6/site-packages
+ export PYTHON=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
+ PYTHON=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
+ export NPY_VER=1.12
+ NPY_VER=1.12
+ export CONDA_NPY=112
+ CONDA_NPY=112
+ export PERL_VER=5.26
+ PERL_VER=5.26
+ export CONDA_PERL=5.26
+ CONDA_PERL=5.26
+ export LUA_VER=5
+ LUA_VER=5
+ export CONDA_LUA=5
+ CONDA_LUA=5
+ export R_VER=3.4
+ R_VER=3.4
+ export CONDA_R=3.4
+ CONDA_R=3.4
+ export SKA_TOP_SRC_DIR=/data/baffin/tom/git/skare3/src
+ SKA_TOP_SRC_DIR=/data/baffin/tom/git/skare3/src
+ export GIT_DESCRIBE_TAG=3.5.3
+ GIT_DESCRIBE_TAG=3.5.3
+ export GIT_DESCRIBE_NUMBER=0
+ GIT_DESCRIBE_NUMBER=0
+ export GIT_DESCRIBE_HASH=g5c2f3f2
+ GIT_DESCRIBE_HASH=g5c2f3f2
+ export GIT_FULL_HASH=5c2f3f24f6c4e06dead070f2eab9d5d27b9bd257
+ GIT_FULL_HASH=5c2f3f24f6c4e06dead070f2eab9d5d27b9bd257
+ export GIT_BUILD_STR=0_g5c2f3f2
+ GIT_BUILD_STR=0_g5c2f3f2
+ export PKG_NAME=ska.ftp
+ PKG_NAME=ska.ftp
+ export PKG_VERSION=3.5.3
+ PKG_VERSION=3.5.3
+ export PKG_BUILDNUM=0
+ PKG_BUILDNUM=0
+ export PKG_BUILD_STRING=placeholder
+ PKG_BUILD_STRING=placeholder
+ export PKG_HASH=1234567
+ PKG_HASH=1234567
+ export RECIPE_DIR=/data/baffin/tom/git/skare3/pkg_defs/Ska.ftp
+ RECIPE_DIR=/data/baffin/tom/git/skare3/pkg_defs/Ska.ftp
+ export CPU_COUNT=12
+ CPU_COUNT=12
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ export SHLIB_EXT=.so
+ SHLIB_EXT=.so
+ export PATH=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p:/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin:/proj/sot/ska3/flight/bin:/export/tom/miniconda3/bin:/home/aldcroft/bin:/home/aldcroft/bin/MST:/soft/saord/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin/X11:/usr/X11R6/bin:.
+ PATH=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p:/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin:/proj/sot/ska3/flight/bin:/export/tom/miniconda3/bin:/home/aldcroft/bin:/home/aldcroft/bin/MST:/soft/saord/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin/X11:/usr/X11R6/bin:.
+ export HOME=/home/aldcroft
+ HOME=/home/aldcroft
+ export PKG_CONFIG_PATH=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/pkgconfig
+ PKG_CONFIG_PATH=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/pkgconfig
+ export 'CMAKE_GENERATOR=Unix Makefiles'
+ CMAKE_GENERATOR='Unix Makefiles'
+ export DISPLAY=:53
+ DISPLAY=:53
+ export LD_RUN_PATH=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib
+ LD_RUN_PATH=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib
+ export BUILD=x86_64-conda_cos6-linux-gnu
+ BUILD=x86_64-conda_cos6-linux-gnu
+ export r_base=3.4
+ r_base=3.4
+ export cpu_optimization_target=nocona
+ cpu_optimization_target=nocona
+ export target_platform=linux-64
+ target_platform=linux-64
+ export 'pin_run_as_build={'\''python'\'': {'\''min_pin'\'': '\''x.x'\'', '\''max_pin'\'': '\''x.x'\''}}'
+ pin_run_as_build='{'\''python'\'': {'\''min_pin'\'': '\''x.x'\'', '\''max_pin'\'': '\''x.x'\''}}'
+ export CONDA_BUILD_STATE=BUILD
+ CONDA_BUILD_STATE=BUILD
+ source /proj/sot/ska3/flight/bin/activate /data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
++ [[ -n 4.2.46(2)-release ]]
++ _SCRIPT_LOCATION=/proj/sot/ska3/flight/bin/activate
++ _SHELL=bash
+++ dirname /proj/sot/ska3/flight/bin/activate
++ _CONDA_DIR=/proj/sot/ska3/flight/bin
++ '[' 1 -gt 1 ']'
++ case "$(uname -s)" in
+++ uname -s
++ EXT=
++ export _CONDA_PYTHON=/proj/sot/ska3/flight/bin/python
++ _CONDA_PYTHON=/proj/sot/ska3/flight/bin/python
++ [[ -n 4.2.46(2)-release ]]
+++ basename /data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/work/conda_build.sh
++ [[ conda_build.sh == \a\c\t\i\v\a\t\e ]]
++ '[' 1 -eq 0 ']'
++ args=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
++ /proj/sot/ska3/flight/bin/conda ..checkenv bash /data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
++ ((  0 != 0  ))
++ _CONDA_HOLD=true
++ source /proj/sot/ska3/flight/bin/deactivate
+++ [[ -n 4.2.46(2)-release ]]
+++ _SCRIPT_LOCATION=/proj/sot/ska3/flight/bin/deactivate
+++ _SHELL=bash
++++ dirname /proj/sot/ska3/flight/bin/deactivate
+++ _CONDA_DIR=/proj/sot/ska3/flight/bin
+++ case "$(uname -s)" in
++++ uname -s
+++ EXT=
+++ [[ 1 > 0 ]]
+++ key=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
+++ case $key in
+++ shift
+++ [[ 0 > 0 ]]
+++ [[ -n 4.2.46(2)-release ]]
++++ basename /data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/work/conda_build.sh
+++ [[ conda_build.sh == \d\e\a\c\t\i\v\a\t\e ]]
+++ [[ -z '' ]]
+++ [[ -n 4.2.46(2)-release ]]
++++ basename /data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/work/conda_build.sh
+++ [[ conda_build.sh == \d\e\a\c\t\i\v\a\t\e ]]
+++ return 0
++ unset _CONDA_HOLD
+++ /proj/sot/ska3/flight/bin/conda ..activate bash /data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
++ _NEW_PART=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin
++ ((  0 == 0  ))
++ export CONDA_PATH_BACKUP=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p:/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin:/proj/sot/ska3/flight/bin:/export/tom/miniconda3/bin:/home/aldcroft/bin:/home/aldcroft/bin/MST:/soft/saord/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin/X11:/usr/X11R6/bin:.
++ CONDA_PATH_BACKUP=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p:/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin:/proj/sot/ska3/flight/bin:/export/tom/miniconda3/bin:/home/aldcroft/bin:/home/aldcroft/bin/MST:/soft/saord/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin/X11:/usr/X11R6/bin:.
++ export CONDA_PS1_BACKUP=
++ CONDA_PS1_BACKUP=
++ [[ /data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p:/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin:/proj/sot/ska3/flight/bin:/export/tom/miniconda3/bin:/home/aldcroft/bin:/home/aldcroft/bin/MST:/soft/saord/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin/X11:/usr/X11R6/bin:. == *\C\O\N\D\A\_\P\A\T\H\_\P\L\A\C\E\H\O\L\D\E\R* ]]
++ export PATH=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin:/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p:/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin:/proj/sot/ska3/flight/bin:/export/tom/miniconda3/bin:/home/aldcroft/bin:/home/aldcroft/bin/MST:/soft/saord/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin/X11:/usr/X11R6/bin:.
++ PATH=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin:/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p:/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin:/proj/sot/ska3/flight/bin:/export/tom/miniconda3/bin:/home/aldcroft/bin:/home/aldcroft/bin/MST:/soft/saord/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin/X11:/usr/X11R6/bin:.
++ [[ '' == */* ]]
++ export CONDA_DEFAULT_ENV=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
++ CONDA_DEFAULT_ENV=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
++ firstpath=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin
+++ echo /data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin
+++ sed 's|/bin$||'
++ export CONDA_PREFIX=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
+++ /proj/sot/ska3/flight/bin/conda ..changeps1
++ '[' 1 = 1 ']'
+++ grep -q CONDA_DEFAULT_ENV
+++ grep -q POWERLINE
++ export 'PS1=(/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p) '
++ PS1='(/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p) '
++ _CONDA_D=/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/etc/conda/activate.d
++ [[ -d /data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/etc/conda/activate.d ]]
++ unset _CONDA_PYTHON
++ unset CONDA_PATH
++ [[ -n 4.2.46(2)-release ]]
++ hash -r
+ python setup.py install --single-version-externally-managed --record=record.txt
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    cmdclass=cmdclass,
  File "/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.6/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.6/site-packages/setuptools/dist.py", line 338, in __init__
    _Distribution.__init__(self, attrs)
  File "/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.6/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.6/site-packages/setuptools/dist.py", line 471, in finalize_options
    ep.load()(self, ep.name, value)
  File "/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.6/site-packages/setuptools_scm/integration.py", line 19, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 117, in get_version
    parsed_version = _do_parse(root, parse)
  File "/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 95, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % root)
LookupError: setuptools-scm was unable to detect version for '/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/work'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
Traceback (most recent call last):
  File "/proj/sot/ska3/flight/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/proj/sot/ska3/flight/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "/proj/sot/ska3/flight/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 379, in execute
    noverify=args.no_verify)
  File "/proj/sot/ska3/flight/lib/python3.6/site-packages/conda_build/api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/proj/sot/ska3/flight/lib/python3.6/site-packages/conda_build/build.py", line 1771, in build_tree
    notest=notest,
  File "/proj/sot/ska3/flight/lib/python3.6/site-packages/conda_build/build.py", line 1121, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir)
  File "/proj/sot/ska3/flight/lib/python3.6/site-packages/conda_build/utils.py", line 678, in check_call_env
    return _func_defaulting_env_to_os_environ(subprocess.check_call, *popenargs, **kwargs)
  File "/proj/sot/ska3/flight/lib/python3.6/site-packages/conda_build/utils.py", line 674, in _func_defaulting_env_to_os_environ
    return func(_args, **kwargs)
  File "/proj/sot/ska3/flight/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '-x', '-e', '/data/baffin/tom/git/skare3/builds/ska.ftp_1589366787580/work/conda_build.sh']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "ska_builder.py", line 147, in <module>
    build_one_package(args.package, tag=args.tag)
  File "ska_builder.py", line 121, in build_one_package
    build_package(name)
  File "ska_builder.py", line 115, in build_package
    subprocess.run(cmd_list, check=True).check_returncode()
  File "/proj/sot/ska3/flight/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['conda', 'build', '/data/baffin/tom/git/skare3/pkg_defs/Ska.ftp', '--croot', '/data/baffin/tom/git/skare3/builds', '--no-test', '--old-build-string', '--no-anaconda-upload', '--numpy', '1.12', '--perl', '5.26.2', '--skip-existing']' returned non-zero exit status 1.
```
**Expected behavior**

**Additional context**

**Comment by javierggt** [comment] 2020-05-13 13:56
I will check.

Without checking, my guess would be that this was caused by the change in PR #329 (which changed build.sh), because these packages build with the release versions.

Are setuptools_scm etc installed in this environment? because we normally do not build within the ska3-flight environment.

**Comment by taldcroft** [comment] 2020-05-13 14:08
And of course there is #289, so maybe just hitting that again.

**Comment by taldcroft** [comment] 2020-05-13 14:11
Ah OK, so in shiny every recipe has a build requirement on `setuptools_scm_git_archive` and that does the trick.  I guess in your current build process having that installed is a prior requirement on the build environment.

**Comment by javierggt** [comment] 2020-05-13 14:17
yes, that sounds like it. I can reproduce your error within /proj/sot/ska3/flight. I can still build within our building environment. The build environment has to be a root environment, and you need to install ska3_builder (https://github.com/sot/skare3/wiki/Ska3-runtime-environment-for-maintainers#setting-up-build-environments).

**Comment by javierggt** [comment] 2020-05-13 14:24
Scratch that. I just checked... and we do not have setuptools-scm in the standard build environment (as aca user). It still builds. So my guess is that your problem comes from not having a build environment as described in the link above.

**Comment by javierggt** [comment] 2020-05-21 12:26
I guess we can close this, right @taldcroft?

**Closed** 2020-05-21 14:15 UTC
Labels: bug
