### ISSUE TITLE
Support osx-arm64 architecture

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#524] opened 2020-11-12 10:42 UTC
With the release of the first set of Macs with Apple silicon, we'll eventually need to support this architecture. Apparently there has been good progress getting the core dependencies building using cross compiling from x86_64.

https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/

**Comment by jeanconn** [comment] 2024-05-29 19:40
I think this is mostly closed by #1351 and the issue isn't helping us move it forward more.

**Closed by jeanconn** 2024-05-29 19:40 UTC
