### ISSUE TITLE
pip refusing to install over conda packages in ska3 masters environment

### ISSUE THREAD

**Issue by jzuhone** [sot/skare3#1297] opened 2024-03-09 22:35 UTC
**Description**

In a ska3 masters/dev environment, pip will not overwrite the conda install with that of a local development package.

**To Reproduce**

```
$ python -m pip install .
Processing /data/acis/ska_pkg/acis_thermal_check
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: acis_thermal_check
  Building wheel for acis_thermal_check (pyproject.toml) ... done
  Created wheel for acis_thermal_check: filename=acis_thermal_check-4.8.2.dev30+gda2d3ef-py3-none-any.whl size=33016129 sha256=ef213b3b1d42e5fe4796e662fb6f1676d5ed72347eb7e6cb2bf14a1324775ca8
  Stored in directory: /tmp/pip-ephem-wheel-cache-ggjt9g4f/wheels/a7/13/83/438d68f06602e3abf24824d79785ceee09520af2f24bc060cc
Successfully built acis_thermal_check
Installing collected packages: acis_thermal_check
  Attempting uninstall: acis_thermal_check
    Found existing installation: acis_thermal_check 4.8.2.dev30+gda2d3ef
    Uninstalling acis_thermal_check-4.8.2.dev30+gda2d3ef:
      Successfully uninstalled acis_thermal_check-4.8.2.dev30+gda2d3ef
Successfully installed acis_thermal_check-4.8.1
```

**Expected behavior**
pip should install the new version. What happens (see above) is that it says it finds an existing dev version (which is completely false), uninstalls it, says it successfully installs the dev version, then it says it successfully installs the original version in conda (mysteriously). In the end it is the conda version that remains.

**Additional context**
On a HEAD LAN Linux machine

**Comment by jzuhone** [comment] 2024-03-09 22:39
Only way I can make this work is to do `conda remove --force acis_thermal_check`, which is undesirable.

**Comment by jeanconn** [comment] 2024-03-10 17:38
I'm working in a "speedy" masters/dev linux env and was not quite able to reproduce this, though I not that it looks like pip uninstalled acis_thermal_check and installed acis-thermal-check.

```
(ska3-test) jeanconn-fido> conda list acis_thermal_check
# packages in environment at /fido.real/conda/envs/ska3-test:
#
# Name                    Version                   Build  Channel
acis_thermal_check        4.8.0                      py_0    https://icxc.cfa.harvard.edu/aspect/ska3-conda/test
(ska3-test) jeanconn-fido> python -m pip install
ERROR: You must give at least one requirement to install (see "pip help install")
(ska3-test) jeanconn-fido> python -m pip install .
Processing /proj/sot/ska/jeanproj/git/acis_thermal_check
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: acis_thermal_check
  Building wheel for acis_thermal_check (pyproject.toml) ... done
  Created wheel for acis_thermal_check: filename=acis_thermal_check-4.8.2.dev26+g561537e-py3-none-any.whl size=33022783 sha256=0ec3502a474888d457380890a105a3fdc8df90e528436732fb99190a1071c8d5
  Stored in directory: /tmp/pip-ephem-wheel-cache-hmvlsx2e/wheels/3e/cb/3a/d393ce06cf3dc6056a28ef4e8c84c1941d83cba3d2a5111f32
Successfully built acis_thermal_check
Installing collected packages: acis_thermal_check
  Attempting uninstall: acis_thermal_check
    Found existing installation: acis-thermal-check 4.8.0
    Uninstalling acis-thermal-check-4.8.0:
      Successfully uninstalled acis-thermal-check-4.8.0
Successfully installed acis_thermal_check-4.8.2.dev26+g561537e
(ska3-test) jeanconn-fido> conda list acis_thermal_check
# packages in environment at /fido.real/conda/envs/ska3-test:
#
# Name                    Version                   Build  Channel
(ska3-test) jeanconn-fido>
(ska3-test) jeanconn-fido> conda list acis
# packages in environment at /fido.real/conda/envs/ska3-test:
#
# Name                    Version                   Build  Channel
acis-thermal-check        4.8.2.dev26+g561537e          pypi_0    pypi
```

**Comment by jeanconn** [comment] 2024-09-19 15:14
I was unable to reproduce this at the time.  Closing as likely fine and can reopen if this recurs.

**Closed by jeanconn** 2024-09-19 15:14 UTC
Labels: bug
