### ISSUE TITLE
Cannot install ska3-perl on Mac, cannot build watch_cron_logs

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#387] opened 2020-07-01 10:59 UTC
**To Reproduce**
```
(ska3-shiny3) ➜  skare3 git:(shiny) ✗ conda create -n ska3-shiny4 -c $ska3conda/shiny ska3-perl 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

PackagesNotFoundError: The following packages are not available from current channels:

  - watch_cron_logs==4.2
```

Then trying to build watch_cron_logs gives this failure:
```
(ska3-shiny3) ➜  skare3 git:(shiny) ✗ python ska_builder.py watch_cron_logs
- Building package watch_cron_logs.
  - Cloning or updating source source watch_cron_logs.
  - Updated repo in /Users/aldcroft/git/skare3/src/watch_cron_logs
  - Auto-checked out at 4.2.1 which is also tip of master
********************************************************************************
watch_cron_logs

python: can't open file 'setup.py': [Errno 2] No such file or directory
  - SKA_PKG_VERSION=
  - conda build /Users/aldcroft/git/skare3/pkg_defs/watch_cron_logs --croot /Users/aldcroft/git/skare3/builds --old-build-string --no-anaconda-upload --python 3.6 --numpy 1.18 --perl 5.26.2 --no-test --skip-existing
********************************************************************************
Copying /Users/aldcroft/git/skare3/src/watch_cron_logs to /Users/aldcroft/git/skare3/builds/watch_cron_logs_1593600559780/work/
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
/Users/aldcroft/miniconda3/envs/ska3-shiny3/lib/python3.6/site-packages/conda_build/environ.py:427: UserWarning: The environment variable 'SKA_TOP_SRC_DIR' is being passed through with value '/Users/aldcroft/git/skare3/src'.  If you are splitting build and test phases with --no-test, please ensure that this value is also set similarly at test time.
  UserWarning
Attempting to finalize metadata for watch_cron_logs
INFO:conda_build.metadata:Attempting to finalize metadata for watch_cron_logs
BUILD START: ['watch_cron_logs-4.2.1-0.tar.bz2']
source tree in: /Users/aldcroft/git/skare3/builds/watch_cron_logs_1593600559780/work
export PREFIX=/Users/aldcroft/git/skare3/builds/watch_cron_logs_1593600559780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
export SRC_DIR=/Users/aldcroft/git/skare3/builds/watch_cron_logs_1593600559780/work
chmod: /Users/aldcroft/git/skare3/builds/watch_cron_logs_1593600559780/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/watch_cron_logs3.pl: Not a directory
Traceback (most recent call last):
  File "/Users/aldcroft/miniconda3/envs/ska3-shiny3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/aldcroft/miniconda3/envs/ska3-shiny3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 469, in main
    execute(sys.argv[1:])
  File "/Users/aldcroft/miniconda3/envs/ska3-shiny3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 460, in execute
    verify=args.verify, variants=args.variants)
  File "/Users/aldcroft/miniconda3/envs/ska3-shiny3/lib/python3.6/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/aldcroft/miniconda3/envs/ska3-shiny3/lib/python3.6/site-packages/conda_build/build.py", line 2344, in build_tree
    notest=notest,
  File "/Users/aldcroft/miniconda3/envs/ska3-shiny3/lib/python3.6/site-packages/conda_build/build.py", line 1492, in build
    cwd=src_dir, stats=build_stats)
  File "/Users/aldcroft/miniconda3/envs/ska3-shiny3/lib/python3.6/site-packages/conda_build/utils.py", line 398, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/aldcroft/miniconda3/envs/ska3-shiny3/lib/python3.6/site-packages/conda_build/utils.py", line 378, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/Users/aldcroft/git/skare3/builds/watch_cron_logs_1593600559780/work/conda_build.sh']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "ska_builder.py", line 164, in <module>
    build_one_package(args.package, tag=args.tag)
  File "ska_builder.py", line 138, in build_one_package
    build_package(name)
  File "ska_builder.py", line 132, in build_package
    subprocess.run(cmd_list, check=True, shell=is_windows).check_returncode()
  File "/Users/aldcroft/miniconda3/envs/ska3-shiny3/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['conda', 'build', '/Users/aldcroft/git/skare3/pkg_defs/watch_cron_logs', '--croot', '/Users/aldcroft/git/skare3/builds', '--old-build-string', '--no-anaconda-upload', '--python', '3.6', '--numpy', '1.18', '--perl', '5.26.2', '--no-test', '--skip-existing']' returned non-zero exit status 1.
```

**Comment by jeanconn** [comment] 2020-07-01 11:26
Yep. I was just as far as starcheck.

**Comment by jeanconn** [comment] 2020-07-01 14:24
Meanwhile, ska3-perl was intended as a production recipe and looks like:

```
requirements:
  run:
    - cfitsio ==3.450
    - xtime ==1.2.2
    - pgplot ==5.2.2 1 # [linux]
    - perl ==5.26.2
    - perl-extutils-f77 ==1.20
    - perl-app-cpanminus ==1.7044
    - perl-core-deps ==0.1
    - perl-pgplot ==2.19 # [linux]
    - perl-dbd-sybase ==1.15 pl526_1 # [linux]
    - perl-chandra-time ==0.9.2
    - perl-app-env-ascds ==0.4
    - perl-cxc-sysarch ==1.0
    - perl-ska-agasc ==3.5.0
    - perl-ska-classic ==0.6
    - perl-ska-convert ==4.3
    - perl-ska-web ==4.0
    - watch_cron_logs ==4.2
    - task_schedule ==4.2.1
```

It was not previously configured for OSX; and ska3-perl was not a requirement for starcheck.  What are our perl requirements on OSX?

**Comment by taldcroft** [comment] 2020-07-01 14:28
Sorry, not really looking into things and just blindly making guesses like that I need `ska3-perl` to install perl and run the perl starcheck app. What do I need to do instead?

**Comment by jeanconn** [comment] 2020-07-01 15:26
Is starcheck the one Perl requirement then, or do we have an actual need for task_schedule etc?   Wondering how to best update the metapackages or instructions in either case.

For starcheck, right now for testing:

- set up environment with at least starcheck and its Python dependencies (proseco, mica, kadi etc or ska3-flight-latest)
- that environment should also have perl-ska-convert (starcheck's bin script is set to print a list of packages to install that are intended to deal with the fact that we don't use the conda dependencies to manage starcheck's perl deps... but I think that output needs update and perl-ska-convert will pull in the necessary stuff for now)
- Make a link such that CONDA_PREFIX/data goes to SKA/data
- Set SKA to just be CONDA_PREFIX

**Comment by jeanconn** [comment] 2020-12-22 21:03
We've flirted with having a ska3-production package, but right now as of shiny promotion the plan is , to run starcheck, install ska3-flight and ska3-perl and it will work on LInux and OSX.  So we can close this issue and re-open if we run into a new problem.

**Closed by jeanconn** 2020-12-22 21:03 UTC
Labels: bug
